CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `number` bigint NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `salt` varchar(255) DEFAULT NULL,
  `role` int DEFAULT NULL,
  `login` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `number_UNIQUE` (`number`)
);
CREATE TABLE `vehicle` (
  `vehicle_id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `vehicle_type` int NOT NULL,
  `vehicle_number` varchar(50) NOT NULL,
  `company` varchar(50) NOT NULL,
  `model` varchar(50) NOT NULL,
  `year` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`vehicle_id`),
  UNIQUE KEY `vehicle_id_UNIQUE` (`vehicle_id`),
  UNIQUE KEY `vehicle_number_UNIQUE` (`vehicle_number`),
  KEY `USER_ID_VEHICLE_FOR_idx` (`user_id`),
  CONSTRAINT `USER_ID_VEHICLE_FOR` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ;

CREATE TABLE `workshop` (
  `workshop_id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `workshop_name` varchar(45) NOT NULL,
  `image` varchar(1000) DEFAULT NULL,
  `city` varchar(20) NOT NULL,
  `state` varchar(20) NOT NULL,
  `country` varchar(20) NOT NULL,
  `address` varchar(200) NOT NULL,
  `latitude` decimal(15,11) NOT NULL,
  `longitude` decimal(15,11) NOT NULL,
  `type` int NOT NULL,
  `open_time` varchar(45) NOT NULL,
  `close_time` varchar(45) NOT NULL,
  `electrical_price` int NOT NULL,
  `engine_price` int NOT NULL,
  `general_price` int NOT NULL,
  `suspension_price` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`workshop_id`),
  UNIQUE KEY `workshop_id_UNIQUE` (`workshop_id`),
  UNIQUE KEY `user_id_UNIQUE` (`user_id`),
  KEY `USER_ID_FOR_KEY_idx` (`user_id`),
  CONSTRAINT `USER_ID_FOR_KEY` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
);
CREATE TABLE `booking` (
  `booking_id` int NOT NULL AUTO_INCREMENT,
  `vehicle_id` int NOT NULL,
  `workshop_id` int DEFAULT NULL,
  `latitude` decimal(15,11) NOT NULL,
  `longitude` decimal(15,11) NOT NULL,
  `booking_city` varchar(30) NOT NULL,
  `booking_state` varchar(25) NOT NULL,
  `booking_country` varchar(20) NOT NULL,
  `booking_address` varchar(200) NOT NULL,
  `request_status` tinyint(1) DEFAULT '1',
  `accept_status` tinyint(1) DEFAULT NULL,
  `problem` varchar(45) NOT NULL,
  `is_live` tinyint(1) DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT '0',
  `otp` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `booking_date` varchar(255) DEFAULT NULL,
  `booking_time` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`booking_id`),
  UNIQUE KEY `booking_id_UNIQUE` (`booking_id`),
  KEY `FK_VEHICLE_ID_idx` (`vehicle_id`),
  KEY `FK_WORKSHOP_ID_idx` (`workshop_id`),
  CONSTRAINT `FK_VEHICLE_ID` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`vehicle_id`),
  CONSTRAINT `FK_WORKSHOP_ID` FOREIGN KEY (`workshop_id`) REFERENCES `workshop` (`workshop_id`)
);
CREATE TABLE `service_details` (
  `service_list_id` int NOT NULL AUTO_INCREMENT,
  `booking_id` int NOT NULL,
  `accept_status` tinyint(1) NOT NULL DEFAULT '0',
  `cancel_status` tinyint(1) DEFAULT '0',
  `cancel_reason` varchar(100) DEFAULT NULL,
  `service_amount` int DEFAULT '0',
  `is_live` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`service_list_id`),
  UNIQUE KEY `service_id_UNIQUE` (`service_list_id`),
  UNIQUE KEY `booking_id_UNIQUE` (`booking_id`),
  KEY `FK_BOOKING_KEY_idx` (`booking_id`),
  CONSTRAINT `FK_BOOKING_KEY` FOREIGN KEY (`booking_id`) REFERENCES `booking` (`booking_id`)
);
CREATE TABLE `service_list` (
  `service_id` int NOT NULL AUTO_INCREMENT,
  `service_detail_id` int NOT NULL,
  `service_name` varchar(45) DEFAULT NULL,
  `service_price` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`service_id`),
  UNIQUE KEY `service_id_UNIQUE` (`service_id`),
  KEY `FK_SERVICE_LIST_ID_idx` (`service_detail_id`),
  CONSTRAINT `FK_SERVICE_LIST_ID` FOREIGN KEY (`service_detail_id`) REFERENCES `service_details` (`service_list_id`)
);

